### ISSUE TITLE
App stops working after a few operations, needs refreshing

### ISSUE THREAD

**Issue by qoobaa** [qoobaa/fakturama#19]
Not sure if it's related or not, but there's a Glimmer exception in the console.

**Comment by lowski** [comment]
@qoobaa any error / stacktrace on the console? Are you able to provide steps to reproduce?

**Comment by lowski** [comment]
@qoobaa could you try if issue still exists after changes from #20?

**Comment by qoobaa** [comment]
It seems to work stable now.

**Comment by qoobaa** [comment]
Thank you!
