### ISSUE TITLE
Invoice preview doesn't display seller and buyer fields properly

### ISSUE THREAD

**Issue by qoobaa** [qoobaa/fakturama#25]
![image](https://user-images.githubusercontent.com/10659/35767428-6d0c12a4-08ec-11e8-9db5-7f4446897859.png)

**Comment by qoobaa** [comment]
![image](https://user-images.githubusercontent.com/10659/35767438-93bc9c8e-08ec-11e8-81f0-68ba2bbde813.png)
… the same invoice in edit mode.

**Comment by lowski** [comment]
PS. I didn't expect so many issues with the upgrade but it looks like we are almost there.

**Comment by qoobaa** [comment]
I wish I had more time to fix these bugs. I'm currently busy with https://github.com/Vizzuality/emissions-scenario-portal, so all I can do is testing and providing some insight. I hope we'll be able to move Fakturama's staging to production soon.

My colleague from Cowbell Labs has told me that they've got a question about the JPK_FA support in Fakturama recently. I think it's crucial if we want to keep the project alive.

Thank you for your support.
