### ISSUE TITLE
Adding comments doesn't work

### ISSUE THREAD

**Issue by mrcnkoba** [qoobaa/fakturama#32]
First of all I wanted to thank you for all the work you've put in Fakturama. It's great and keeps my invoicing tidy.

I spotted an issue that none of my comments are not displayed on the preview/edit view. I peeked and they present in the response from firebase, but they are just not displayed.

**Comment by qoobaa** [comment]
Should be fixed now.

**Comment by mrcnkoba** [comment]
Thanks, you rock.
