### ISSUE TITLE
User is not remember between page refreshes

### ISSUE THREAD

**Issue by lowski** [qoobaa/fakturama#7]
I've noticed it today. When I sign in with Google and then refresh the page, I'm being logged out.

@qoobaa do you think the problem might come from my Firebase configuration?

**Comment by qoobaa** [comment]
Yeah, it's something with the config. I've just deployed the new version to https://staging.fakturama.pl/ - it should be useful for testing.

**Comment by lowski** [comment]
Thanks!

Unfortunately I'm not able log in on staging. Ember is also not very helpful as error is not very descriptive: `undefined`.

**Comment by lowski** [comment]
I was able to dig into the error - it's something about unauthorized domain. I guess it's Firebase misconfiguration.

**Comment by lowski** [comment]
Fixed :)
