### ISSUE TITLE
Problem with fetching records

### ISSUE THREAD

**Issue by lowski** [qoobaa/fakturama#8]
@qoobaa pointed out in #6 :

> It seems to work a bit better now, at least for storing records. Fetches are mostly broken. I've added you to the collaborators list, so you can push to the repo if you need to.

**Comment by lowski** [comment]
@qoobaa can you provide more details? Is it about invoices or clients?

The problem is I was testing it on the empty database :/ so once record was stored, I fixed fetching to work only for that case. That was wrong assumption on my side.

Is it possible to share some dev database with me that is already pre-filled with some data? It would  make re-producing issues easier.

**Comment by qoobaa** [comment]
The easiest way to get some testing data is exporting your DB from the production (settings tab). You should be able to do an import in the new version and see everything there.

**Comment by lowski** [comment]
Ok I was able to reproduce it. It seems that all records are stored without model's name as a root element.

I will take a look at it over the weekend but #7 needs to be fixed first because it's really annoying during development.

**Comment by qoobaa** [comment]
Saving records (e.g. bank accounts) seems to work fine, the DB schema looks good. However, after refreshing the page records don't contain any data - parsing responses must be broken.

**Comment by lowski** [comment]
> However, after refreshing the page records don't contain any data - parsing responses must be broken.

Problem was with computed properties which are used to avoid displaying new records when moving between routes. Fixed in #11
